<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Nasurino.SmartWallet.Api.Tests</RootNamespace>
        <AssemblyName>SmartWallet.Api.Tests</AssemblyName>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SmartWallet\SmartWallet.csproj" />
    </ItemGroup>

</Project>
