<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Nasurino.SmartWallet.Context.Repository.Tests</RootNamespace>
        <AssemblyName>SmartWallet.Context.Repository.Tests</AssemblyName>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DAL\Context.Repository\Context.Repository.csproj" />
      <ProjectReference Include="..\DAL\Context.Tests\Context.Tests.csproj" />
    </ItemGroup>

</Project>