<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <RootNamespace>Nasurino.SmartWallet.Common.Infrastructure</RootNamespace>
	  <AssemblyName>SmartWallet.Common.Infrastructure</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Infrastructure.Contracts\Common.Infrastructure.Contracts.csproj" />
  </ItemGroup>

</Project>