<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <RootNamespace>Nasurino.SmartWallet.Service.Infrastructure</RootNamespace>
	  <AssemblyName>SmartWallet.Service.Infrastructure</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Service.Infrastructure.Contracts\Service.Infrastructure.Contracts.csproj" />
    <ProjectReference Include="..\Service.Models\Service.Models.csproj" />
    <ProjectReference Include="..\SmartWallet.Options\SmartWallet.Options.csproj" />
  </ItemGroup>

</Project>
