<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <RootNamespace>Nasurino.SmartWallet.Services.Infrastructure</RootNamespace>
	  <AssemblyName>SmartWallet.Services.Infrastructure</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SmartWallet.Options\SmartWallet.Options.csproj" />
    <ProjectReference Include="..\Services.Infrastructure.Contracts\Services.Infrastructure.Contracts.csproj" />
  </ItemGroup>

</Project>
