@startuml
!pragma layout smetana
skinparam dpi 300
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Анонимный\nпользователь" as AU
actor "Зарегистрированный\nпользователь" as RU

rectangle "Аутентификация" as Auth {
    usecase "Регистрация" as UC1
    usecase "Вход в систему" as UC2
}

rectangle "Управление профилем" as Profile {
    usecase "Просмотр профиля" as UC3
    usecase "Редактирование профиля" as UC4
    usecase "Смена пароля" as UC5
}

rectangle "Финансовые операции" as Finance {
    usecase "Управление счетами\nи категориями" as UC6
    usecase "Создание транзакции" as UC7
    usecase "Удаление транзакции" as UC8
}

rectangle "Аналитика" as Analytics {
    usecase "Просмотр финансовой\nаналитики" as UC9
}

AU --> UC1
AU --> UC2

RU --> UC2
RU --> UC3
RU --> UC4
RU --> UC5
RU --> UC6
RU --> UC7
RU --> UC8
RU --> UC9
@enduml
