<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Nasurino.SmartWallet.Service.Tests</RootNamespace>
        <AssemblyName>SmartWallet.Service.Tests</AssemblyName>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Ahatornn.TestGenerator" />
      <PackageReference Include="FluentAssertions" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" />
      <PackageReference Include="Microsoft.Testing.Platform" />
      <PackageReference Include="Moq" />
      <PackageReference Include="xunit" />
      <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Services.Infrastructure\Service.Infrastructure.csproj" />
      <ProjectReference Include="..\Services\Services.csproj" />
      <ProjectReference Include="..\UnitTests.Services.Infrastructure\UnitTests.Services.Infrastructure.csproj" />
    </ItemGroup>

</Project>